name: CD

on:
 push:
   branches: [ main, master ]

jobs:
  build:
    runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
       node-version: '14.x'
   - name: Install dependencies
     run: npm ci
   - name: Install sharp
     run: npm install sharp
   - name: Run next dev
     run: next dev
   - name: Run next dev
     run: next dev
   - name: Run next build
     run: next build
   - name: Run next start
     run: next start
